'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
export default function EditContent({content}:{content:any}){
 const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({originalTitle:content.originalTitle||content.title,englishTitle:content.englishTitle||content.title,thaiTitle:content.thaiTitle||'',displayTitle:content.displayTitle||content.englishTitle||content.title,description:content.description||'',posterUrl:content.posterUrl||'',backdropUrl:content.backdropUrl||'',contentType:content.contentType||'VIDEO',year:content.year||''});
 const router=useRouter();
 const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 async function save(){setSaving(true);setError('');const r=await fetch(`/api/content/${content.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const j=await r.json();setSaving(false);if(!r.ok){setError(j.error||'Save failed');return}setOpen(false);router.refresh()}
 return <div className="content-editor"><button className="btn secondary" onClick={()=>setOpen(v=>!v)}>{open?'Close editor':'Edit details'}</button>{open&&<div className="form-card editor-panel"><div className="form-grid"><input className="input" value={form.originalTitle} onChange={e=>set('originalTitle',e.target.value)} placeholder="Original title"/><input className="input" value={form.englishTitle} onChange={e=>set('englishTitle',e.target.value)} placeholder="English title"/><input className="input" value={form.thaiTitle} onChange={e=>set('thaiTitle',e.target.value)} placeholder="Thai title"/><input className="input" value={form.displayTitle} onChange={e=>set('displayTitle',e.target.value)} placeholder="Display title"/><input className="input" value={String(form.year)} onChange={e=>set('year',e.target.value)} placeholder="Year"/><select className="input" value={form.contentType} onChange={e=>set('contentType',e.target.value)}><option value="SERIES">Series</option><option value="MOVIE">Movie</option><option value="CLIP">Video Clip</option><option value="VIDEO">Video</option></select><input className="input" value={form.posterUrl} onChange={e=>set('posterUrl',e.target.value)} placeholder="Poster URL"/><input className="input" value={form.backdropUrl} onChange={e=>set('backdropUrl',e.target.value)} placeholder="Backdrop URL"/></div><textarea className="input editor-textarea" value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Description"/><button className="btn" onClick={save} disabled={saving}>{saving?'Saving...':'Save changes'}</button>{error&&<p className="error">{error}</p>}</div>}</div>
}
