'use client';
import {useEffect,useState} from 'react';import {useRouter} from 'next/navigation';
type Cat={id:string;name:string};
type Source={id:string;name:string;url:string;scanWindow:number;scanIntervalHours:number;enabled:boolean;lastScannedAt:string|null;lastError:string|null;lastScanCount:number;categories:{category:Cat}[]};
type EditState={id:string;name:string;url:string;scanWindow:string;interval:string;categoryIds:string[];enabled:boolean};
const windows=['7','15','30'];
const intervals=[['6','every 6 hours'],['12','every 12 hours'],['24','daily'],['48','every 2 days'],['168','weekly']];
export default function Sources(){
 const [sources,setSources]=useState<Source[]>([]),[cats,setCats]=useState<Cat[]>([]),[name,setName]=useState(''),[url,setUrl]=useState(''),[window,setWindow]=useState('30'),[selected,setSelected]=useState<string[]>([]),[interval,setInterval]=useState('24'),[error,setError]=useState(''),[edit,setEdit]=useState<EditState|null>(null),[saving,setSaving]=useState(false);
 const router=useRouter();
 async function load(){const [a,b]=await Promise.all([fetch('/api/sources'),fetch('/api/categories')]);if(a.status===401){router.push('/login');return}setSources(await a.json());setCats(await b.json())}
 useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();setError('');const r=await fetch('/api/sources',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,url,scanWindow:Number(window),scanIntervalHours:Number(interval),categoryIds:selected})});const j=await r.json();if(!r.ok){setError(j.error);return}setName('');setUrl('');setSelected([]);await load()}
 async function scan(id:string){setError('');const r=await fetch('/api/scan-source',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sourceId:id})});const j=await r.json();if(!r.ok)setError(j.error||'Scan failed');await load()}
 async function remove(id:string){if(!confirm('Delete this source?'))return;await fetch('/api/sources?id='+id,{method:'DELETE'});if(edit?.id===id)setEdit(null);load()}
 function startEdit(s:Source){setError('');setEdit({id:s.id,name:s.name,url:s.url,scanWindow:String(s.scanWindow),interval:String(s.scanIntervalHours||24),categoryIds:s.categories.map(x=>x.category.id),enabled:s.enabled})}
 async function saveEdit(){if(!edit)return;setSaving(true);setError('');try{const r=await fetch('/api/sources',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({id:edit.id,name:edit.name,url:edit.url,scanWindow:Number(edit.scanWindow),scanIntervalHours:Number(edit.interval),categoryIds:edit.categoryIds,enabled:edit.enabled})});const j=await r.json();if(!r.ok){setError(j.error||'Failed to update source');return}setEdit(null);await load()}finally{setSaving(false)}}
 async function toggleEnabled(s:Source){setError('');const r=await fetch('/api/sources',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({id:s.id,enabled:!s.enabled,name:s.name,url:s.url,scanWindow:s.scanWindow,scanIntervalHours:s.scanIntervalHours,categoryIds:s.categories.map(x=>x.category.id)})});if(!r.ok){const j=await r.json().catch(()=>({}));setError(j.error||'Failed to update source');return}load()}
 return <main className="container">
  <div className="page-head"><div><div className="eyebrow">CONTENT SOURCES</div><h1>Sources</h1><p className="muted">Add websites once. Edit their scan policy, categories, or enabled state at any time.</p></div></div>
  <section className="form-card"><h2>Add source</h2><div className="form-grid"><input className="input" placeholder="Source name" value={name} onChange={e=>setName(e.target.value)}/><input className="input" placeholder="https://example.com" value={url} onChange={e=>setUrl(e.target.value)}/><select className="input" value={window} onChange={e=>setWindow(e.target.value)}><option value="7">Last 7 days</option><option value="15">Last 15 days</option><option value="30">Last 30 days</option></select><select className="input" value={interval} onChange={e=>setInterval(e.target.value)}>{intervals.map(([v,l])=><option key={v} value={v}>Scan {l}</option>)}</select></div><div className="label">Categories</div><div className="check-grid">{cats.map(c=><label key={c.id} className="check"><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,c.id]:v.filter(x=>x!==c.id))}/>{c.name}</label>)}{!cats.length&&<span className="muted">Create categories first if you want to tag this source.</span>}</div><button className="btn" onClick={add}>Save source</button>{error&&<p className="error">{error}</p>}</section>
  <div className="grid">{sources.map(s=><article className="card" key={s.id}>
   <div className="row space"><div><h3>{s.name}</h3><div className="muted wrap">{s.url}</div></div><span className={s.enabled?'ok':'muted'}>{s.enabled?'Enabled':'Paused'}</span></div>
   <p>Scan window: <strong>{s.scanWindow} days</strong> · Schedule: <strong>{s.scanIntervalHours ? 'every '+s.scanIntervalHours+'h' : 'daily'}</strong></p>
   <div>{s.categories.map(c=><span className="tag" key={c.category.id}>{c.category.name}</span>)}</div>
   <p className="muted small">{s.lastScanCount||0} items found on last scan</p>
   <div className="row" style={{flexWrap:'wrap'}}><button className="btn secondary" onClick={()=>scan(s.id)} disabled={!s.enabled}>Scan now</button><button className="btn secondary" onClick={()=>startEdit(s)}>Edit</button><button className="iconbtn" onClick={()=>toggleEnabled(s)} aria-label={s.enabled?'Pause source':'Enable source'}>{s.enabled?'Ⅱ':'▶'}</button><button className="iconbtn" onClick={()=>remove(s.id)} aria-label={'Delete '+s.name}>×</button></div>
   <p className={s.lastError?'error':'ok'}>{s.lastError||(s.lastScannedAt?'Last scan '+new Date(s.lastScannedAt).toLocaleString():'Ready for first scan')}</p>
   {edit?.id===s.id&&<div className="form-card editor-panel"><h3>Edit source</h3><div className="form-grid"><input className="input" value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/><input className="input" value={edit.url} onChange={e=>setEdit({...edit,url:e.target.value})}/><select className="input" value={edit.scanWindow} onChange={e=>setEdit({...edit,scanWindow:e.target.value})}>{windows.map(v=><option key={v} value={v}>Last {v} days</option>)}</select><select className="input" value={edit.interval} onChange={e=>setEdit({...edit,interval:e.target.value})}>{intervals.map(([v,l])=><option key={v} value={v}>Scan {l}</option>)}</select></div><div className="label">Categories</div><div className="check-grid">{cats.map(c=><label key={c.id} className="check"><input type="checkbox" checked={edit.categoryIds.includes(c.id)} onChange={e=>setEdit({...edit,categoryIds:e.target.checked?[...edit.categoryIds,c.id]:edit.categoryIds.filter(x=>x!==c.id)})}/>{c.name}</label>)}</div><label className="check"><input type="checkbox" checked={edit.enabled} onChange={e=>setEdit({...edit,enabled:e.target.checked})}/> Enabled</label><div className="row"><button className="btn" onClick={saveEdit} disabled={saving}>{saving?'Saving…':'Save changes'}</button><button className="btn secondary" onClick={()=>setEdit(null)} disabled={saving}>Cancel</button></div></div>}
  </article>)}{!sources.length&&<div className="empty">No sources yet.</div>}</div>
 </main>
}
